<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
  'Taxonomy\Module'                                     => __DIR__ . '/Module.php',
  'Taxonomy\Controller\IndexController'                 => __DIR__ . '/src/Taxonomy/Controller/IndexController.php',
  'Taxonomy\Controller\Plugin\TaxonomyPlugin'           => __DIR__ . '/src/Taxonomy/Controller/Plugin/TaxonomyPlugin.php',
  'Taxonomy\Entity\Term'                                => __DIR__ . '/src/Taxonomy/Entity/Term.php',
  'Taxonomy\Entity\TermTaxonomy'                        => __DIR__ . '/src/Taxonomy/Entity/TermTaxonomy.php',
  'Taxonomy\Form\AddTaxonomyForm'                       => __DIR__ . '/src/Taxonomy/Form/AddTaxonomyForm.php',
  'Taxonomy\Form\TermFieldset'                          => __DIR__ . '/src/Taxonomy/Form/TermFieldset.php',
  'Taxonomy\Form\TermTaxonomyFieldset'                  => __DIR__ . '/src/Taxonomy/Form/TermTaxonomyFieldset.php',
  'Taxonomy\Options\ModuleOptions'                      => __DIR__ . '/src/Taxonomy/Options/ModuleOptions.php',
  'Taxonomy\Options\TaxonomyControllerOptionsInterface' => __DIR__ . '/src/Taxonomy/Options/TaxonomyControllerOptionsInterface.php',
);
