<?php
$title = 'Thêm taxon';
$this->headTitle($title);
?>
<h1><?php echo $this->escapeHtml($title); ?></h1>
<?php
$form->setAttribute('action', $this->url('domain/index/crud', array('tax'=>$tax,'action' => 'add')));
$form->prepare();

echo $this->form()->openTag($form);
$taxonomy = $form->get('taxonomy');
$term = $taxonomy->get('term');
echo $this->formRow($term->get('name'));
echo $this->formRow($term->get('slug'));
echo $this->formRow($taxonomy->get('description'));

$parent = $taxonomy->get('parent');
$parent->setValueOptions($valueOptions);
echo $this->formRow($parent);

echo $this->formHidden($form->get('csrf'));
echo $this->formSubmit($form->get('submit'));
echo $this->form()->closeTag();