<?php

 $title = 'TERM';
 $this->headTitle($title);
 ?>
 <h1><?php echo $this->escapeHtml($title); ?></h1>
 <p>
     <a href="<?php echo $this->url('', array('action'=>'add'));?>">Add term</a>
 </p>
<form method="post">
 <table class="table">
 <tr>
     
     <th>Name</th>
     <th>Slug</th>
     <th>Term Group</th>
     <th>&nbsp;</th>
     <th>Xóa</th>
 </tr> 
 <?php foreach ($zfTerms as $zfTerm):?>
 <tr>     
     <td><?php echo $this->escapeHtml($zfTerm->getName());?></td>
     
     <td><?php echo $this->escapeHtml($zfTerm->getSlug());?></td>
     <td><?php echo $this->escapeHtml($zfTerm->getTermGroup());?></td>     
     <td>
         <a href="<?php echo $this->url('',
             array('action'=>'edit', 'id' => $zfTerm->getTermId()));?>">Sửa</a>
         <a href="<?php echo $this->url('',
             array('action'=>'delete', 'id' => $zfTerm->getTermId()));?>">Xóa</a>
     </td>
     <td>
        <input type="checkbox" name="chk[]" value="<?php echo $zfTerm->getTermId();?>"></input>
     </td>
 </tr>
 <?php endforeach; ?>
 <tr>
    <td colspan="5">        
        <input type="submit" name="del" value="Xóa">
    </td>    
</tr>
 </table>
</form> 
